### ISSUE TITLE
ImagePullBackOff error status when using hint in class_4

### ISSUE THREAD

**Issue by jatoko** [johscheuer/inovex_classes#1]
When using the hint in class_4 the pull policy is set to **"Always"** what leads to following error:
```
$ kubectl get po
NAME                      READY     STATUS             RESTARTS   AGE
gowiki-################   0/1       ImagePullBackOff   0          0s
```

Suggestion:
change to `--image-pull-policy=IfNotPresent`
-> "**HINT** you can use `kubectl run --image johscheuer/gowiki:v1 --expose --port 8080 --replicas 1 -o yaml --dry-run --image-pull-policy=IfNotPresent gowiki` for a skeleton."

**Comment by johscheuer** [comment]
Thanks for reporting, I fixed this issue in https://github.com/johscheuer/inovex_classes/commit/cfa4db37f928544f7c6a19f8e6146f03914a202c
